version: "3"

volumes:
    #nodemodules: {}

services:
  venom_api:
    build:
        context: .
    ports:
      - 8088:8000
    volumes:
      - .:/usr/src/app
      #- nodemodules:/usr/src/app/node_modules